function resultToMarkdown(result, lang) {
  if (!result) return '';
  var L = lang === 'en';
  var lines = [
    '# ' + (result.title || (L ? 'Project Idea' : 'Идея проекта')),
    '',
    '**' + (L ? 'Problem' : 'Проблема') + ':** ' + (result.problem || '—'),
    '**' + (L ? 'Method' : 'Метод') + ':** ' + (result.method || '—'),
    '**' + (L ? 'Application' : 'Применение') + ':** ' + (result.application || '—'),
    '**' + (L ? 'Format' : 'Формат') + ':** ' + (result.format || '—'),
  ];
  if (result.goal) lines.push('**' + (L ? 'Goal' : 'Цель') + ':** ' + result.goal);
  if (result.tasks && result.tasks.length) {
    lines.push('');
    lines.push('## ' + (L ? 'Task Distribution' : 'Распределение задач'));
    result.tasks.forEach(function(t) {
      lines.push('- **' + t.name + '** (' + t.role + '): ' + t.task);
    });
  }
  if (result.aiComment) {
    lines.push('');
    lines.push('---');
    lines.push('*' + (L ? 'AI Comment' : 'Комментарий ИИ') + ':* ' + result.aiComment);
  }
  lines.push('');
  lines.push('---');
  lines.push('*' + (L ? 'Generated by ГИДТПМ' : 'Сгенерировано ГИДТПМ') + ' · ' + new Date().toLocaleDateString(L ? 'en-US' : 'ru-RU') + '*');
  return lines.join('\n');
}

function copyToClipboard(text) {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text).then(function() { return true; }).catch(function() { return fallbackCopy(text); });
  }
  return Promise.resolve(fallbackCopy(text));
}

function fallbackCopy(text) {
  var ta = document.createElement('textarea');
  ta.value = text;
  ta.style.cssText = 'position:fixed;opacity:0;top:0;left:0;width:1px;height:1px';
  document.body.appendChild(ta);
  ta.focus();
  ta.select();
  var ok = false;
  try { ok = document.execCommand('copy'); } catch(e) {}
  document.body.removeChild(ta);
  return ok;
}

function downloadAsMarkdown(text, filename) {
  filename = filename || 'idea.md';
  var blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(function() { URL.revokeObjectURL(url); }, 1000);
}

function shareIdea(text, title) {
  if (navigator.share) {
    return navigator.share({ title: title || 'ГИДТПМ', text: text }).then(function() { return true; }).catch(function() { return false; });
  }
  return Promise.resolve(false);
}

function loadFavorites() {
  try { return JSON.parse(localStorage.getItem('gidtpm_favorites') || '[]'); } catch { return []; }
}

function saveFavorites(list) {
  localStorage.setItem('gidtpm_favorites', JSON.stringify(list));
}

function addToFavorites(result) {
  var list = loadFavorites();
  var item = { id: Date.now(), date: new Date().toISOString(), title: result.title || 'Без названия', mode: result.mode || 'solo', data: result };
  list.unshift(item);
  if (list.length > 50) list.pop();
  saveFavorites(list);
  return list;
}

function removeFromFavorites(id) {
  var list = loadFavorites().filter(function(f) { return f.id !== id; });
  saveFavorites(list);
  return list;
}
